// Generate ../web_embed.h — embed index.html/style.css/app.js as PROGMEM strings
// served by the ESP32 WiFi AP gateway. Run: node build-embed.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = join(__dirname, '..', 'web_embed.h');

const files = [
  { name: 'WEB_INDEX', file: 'index.html' },
  { name: 'WEB_CSS',   file: 'style.css' },
  { name: 'WEB_JS',    file: 'app.js' },
];

let h = `// AUTO-GENERATED by fumhood-web/build-embed.mjs — DO NOT EDIT
// Embedded web app served by the WiFi AP gateway (http://192.168.4.1)
#ifndef WEB_EMBED_H
#define WEB_EMBED_H
#include <pgmspace.h>
`;

for (const { name, file } of files) {
  const src = readFileSync(join(__dirname, file), 'utf8');
  if (src.includes(')FHWEB"')) throw new Error(`${file} contains raw-string delimiter`);
  h += `\nstatic const char ${name}[] PROGMEM = R"FHWEB(${src})FHWEB";\n`;
}
h += '\n#endif // WEB_EMBED_H\n';
writeFileSync(out, h);
const kb = (Buffer.byteLength(h) / 1024).toFixed(1);
console.log(`web_embed.h written (${kb} KB)`);
